### PR TITLE
prettier + tslint on commit

### LINKED ISSUE #122: Add linter for source code
It would be good to have a linter to follow the same code styleguide.  https://eslint.org/

For smart contracts solhint can be used https://github.com/protofire/solhint

### PR DESCRIPTION
**Pull request by tspoff**
Fix #122

### CODE REVIEW

**Comment by AugustoL** [comment]
We should add a script to run the linter right? and maybe instructions on how to run in the readme?

**Comment by tspoff** [comment]
The linter is automatically run in a pre-commit git hook (This is what husky does)

True, it wouldn't hurt to have a script + instructions to do manually. I can cook that up.

**Comment by tspoff** [comment]
Is this ready for approval? @AugustoL

**Comment by AugustoL** [comment]
@tspoff can you add the scripts and instructions in readme?

**Comment by tspoff** [comment]
@AugustoL Updated

**Pull request merged**
