### PR TITLE
Fix issues

### LINKED ISSUE #45: Dxdao Icon should be clickable wich would redirect to the main page
Currently if I wanna click on:

Screenshot 2020-03-18 at 19 19 11

Nothing happens. I would like to see a redirect to the main dxdao.eth page.

### LINKED ISSUE #49: Balance should always have 3 digit decimals
Currently we show either 2 decimals like here (Percentage 24h change indicator should **not** change) :

Screenshot 2020-03-18 at 20 17 04

or
Screenshot 2020-03-18 at 20 17 08

or

Screenshot 2020-03-18 at 20 17 11

### PR DESCRIPTION
**Pull request by AugustoL**
fix #49 fix #45

### CODE REVIEW

**Comment by AugustoL** [comment]
fix #43

**Comment by AugustoL** [comment]
fix #46

**Comment by pimato** [comment]
Hey @AugustoL thanks a lot for your contribution. 
I just checked the navigation styling and and it stopped moving around but a few things moved to other positions. Please see:

Screenshot 2020-03-21 at 15 47 58

the Dxdao logo font should be aligned with the Navigation text.
Also the navigation text moved far to the right compared to the old version.

**Comment by pimato** [comment]
Regarding the fix for https://github.com/levelkdev/BC-DAPP/issues/49 : 

there are still prices and amount throughout the dapp where we did not apply the three decimals:

For example:
Screenshot 2020-03-21 at 15 52 43

Screenshot 2020-03-21 at 15 52 46

Screenshot 2020-03-21 at 15 53 02

**Comment by pimato** [comment]
Fix for https://github.com/levelkdev/BC-DAPP/issues/43 doesn`t work for me and brakes the frontend:

1. Go to metamask and switch address
2. Frontend auto refreshes every few seconds which seems like brakes the whole frontend

**Comment by jpkcambridge** [comment]
Addresses alignment and spacing issues in Navbar.  Related to https://github.com/levelkdev/BC-DAPP/issues/46

**Comment by AugustoL** [comment]
@pimato I cannot reproduce the autorefresh every few seconds, I added an event listener that executes `window.location.reload()` when the address of metamask change. Im on brave+linux.

**Comment by AugustoL** [comment]
@pimato Yes, the other numbers seems to be just hardcoded, thats why I formatted them, only the ones in trade history.

**Comment by jpkcambridge** [comment]
Updates addressing https://github.com/levelkdev/BC-DAPP/issues/49

There is a meeting later today to discuss more holistically our approach to storing/formatting numbers.

**Comment by jpkcambridge** [comment]
> @pimato I cannot reproduce the autorefresh every few seconds, I added an event listener that executes `window.location.reload()` when the address of metamask change. Im on brave+linux.

@AugustoL I am also seeing a refresh problem.  I think we should pull out the ` window.location.reload()` from this PR and address it separately in another PR.

**Comment by AugustoL** [comment]
@jpkcambridge rmeoved the account changed commit. ready to merge?

**Pull request merged**
